---
- name: Install Consul
  hosts: all
  vars:
    CONSUL_VERSION: 1.6.1
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install unzip
      apt:
        name: unzip
        state: present
    - name: Download consul bianry and extact
      unarchive:
        src: https://releases.hashicorp.com/consul/{{ CONSUL_VERSION }}/consul_{{ CONSUL_VERSION }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
    - name: Create Unit file
      template:
        src: ../consul.service
        dest: /lib/systemd/system/consul.service
        mode: 644
      #notify:
      #  - reload systemctl
    - name: Enable and relaod consul service
      systemd:
        name: consul
        enabled: yes
        daemon_reload: yes
    - name: Create directory
      file:
        path: /etc/systemd/system/consul.d
        state: directory

- name: Install Consul Server Tasks
  hosts: consul-servers
  tasks:
    - name: Create server config file
      template:
        src: ./templates/server-config.json
        dest: /etc/systemd/system/consul.d/init.json
    - name: Start consul service
      systemd:
        name: consul
        state: started

- name: Install Consul Client Tasks
  hosts: consul-clients
  tasks:
    - name: Create client config file
      template:
        src: ./templates/client-config.json
        dest: /etc/systemd/system/consul.d/init.json
    - name: Start consul service
      systemd:
        name: consul
        state: started
