---
# Ansible playbook for an semaphore server.
#
# @author Cory Stein (2019).

- hosts: semaphore
  gather_facts: yes
  become: yes

  vars:
    awx_version: "devel"
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - semaphore
