# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure("2") do |config|
  N = 3
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|
      machine.vm.box = "bento/ubuntu-16.04"
      machine.vm.hostname = "machine#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.99.10#{machine_id}"
      machine.vm.network :forwarded_port, guest: 22, host: "220#{machine_id}", id: "ssh"

      machine.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        #v.customize ["modifyvm", :id, "--name", "consul-server"]
      end

      # Set VM and hostnames
      if machine_id == 1
        machine.vm.hostname = "consul-server"
      else 
        machine.vm.hostname = "client#{machine_id}"
      end

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = "2.0"
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "ansible/main.yml"
          ansible.inventory_path = "ansible/inventory"
          ansible.become = true
        end
      end
    end

    config.vm.post_up_message = "Server [machine#{machine_id}] is ready!"

  end

end
