---
dependencies: []

galaxy_info:
  author: corystein
  description: Semaphore repository for RHEL/CentOS.
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 5
        - 6
        - 7
  galaxy_tags:
    - tools
